apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. Will be used in deployment below.
  name: {{ .Values.pvc.name }}
  labels:
    app: minio-storage-claim
spec:
  # Read more about access modes here: https://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    - {{ .Values.pv.accessModes }}
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: {{ .Values.pv.storage }}
  # Uncomment and add storageClass specific to your requirements below. Read more https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  # storageClassName: minio
