ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - rainbow-drone.vpc123.xyz

sourceControl:
  provider: github
#  gogs:
#    server: http://gogs.kakj.com
  github:
    clientID: 4c66c038e8dc7a507de5
    clientSecretKey: vpc123
    clientSecretValue: db2f0c975799769ebfc9e6545c2042324c8e6060
    server: http://github.com

service:
  httpPort: 8082

server:
  adminUser: kakj-go
  ## Configures drone to use kubernetes to run pipelines rather than agents, if enabled
  ## will not deploy any agents.
  kubernetes:
    ## set to true if you want drone to use kubernetes to run pipelines
    enabled: true
  host: rainbow-drone.vpc123.xyz
  protocol: http

persistence:
  enabled: true
  storageClass: "rook-ceph-block"

sharedSecret: c7634c78eda8891d1d11d5f1f64e6753
