apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nodeport }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.minio.port }}
      targetPort: {{ .Values.global.minio.port }}
      protocol: TCP
  selector:
    app: {{ .Values.service.name }}
