apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.global.nginx.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.global.nginx.port }}
    targetPort: {{ .Values.global.nginx.port }}
