replicas: 1
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 150m
    memory: 150Mi

service:
  name: nginx-svc

ingress:
  name: nginx-ingress
  host: traefik.dracula.io

# 请不要修改此配置
global:
  namespace: nginx-ns
  nginx:
    name: nginx-ds
    replicas: 1
    image: nginx
    tag: alpine
    port: 80
