apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik.gitlab.io 
    http:
      paths:
      - backend:
          serviceName: gitlab-ce-gitlab-ce
          servicePort: 80
